### ISSUE TITLE
Aeson 2 support

### ISSUE THREAD

**Issue by theophile-scrive** [L0neGamer/ekg#90]
Hi! my organisation is depending on this library and we would like to provide a patch to support Aeson 2. Would you be open to this? :)

**Comment by erikd** [comment]
I am not a maintainer of this project, but yes, have support for `aeson >= 2.0` would be a huge plus.

**Comment by andreabedini** [comment]
AFAIK this only needs a revision, most of IOG's repos do `allow-newer: ekg:aeson`.

**Comment by theophile-scrive** [comment]
@tibbe hopeful ping? :)
